[System.Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkeyU64_UIA.exe", ".\Crossfirer_Shooter.ahk")
[System.Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkeyU64_UIA.exe", ".\Crossfirer_C4_Hero.ahk")
[System.Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkeyU64_UIA.exe", ".\Crossfirer_Bhop.ahk")
[System.Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkeyU64_UIA.exe", ".\Crossfirer_Clicker.ahk")
[System.Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkeyU64_UIA.exe", ".\Crossfirer_Recoilless.ahk")
[System.Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkeyU64_UIA.exe", ".\Crossfirer_NetBlocker.ahk")
# [System.Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkeyU64_UIA.exe", ".\Crossfirer_LR_RCL.ahk")
[System.Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkeyU64_UIA.exe", ".\Crossfirer_Controller.ahk")